### ISSUE TITLE
Consider changing to a permissive license?

### ISSUE THREAD

**Issue by wesm** [ufal/unilib#2]
We've been surveying UTF-8 utility libraries for C/C++ for use in Apache Arrow, and we are interested in unilib but unfortunately the MPL 2.0 is problematic for Apache projects (it's not impossible, but definitely frowned upon https://www.apache.org/legal/resolved.html#weak-copyleft-licenses, and could create problems for people/companies who depend on the project and want to know that all of the transitive dependencies are roughly on the same foot licensing wise). Would you consider changing the license to Apache 2.0, BSD 2/3 clause, or MIT?

**Comment by foxik** [comment]
I am sorry, but I am quite happy with MPL, notably with the source-level copyleft, so I am not planning to change it.

**Comment by wesm** [comment]
OK thanks. I hope you change your mind in the future. Users are an open source project's most valuable commodity.

**Comment by foxik** [comment]
@wesm My view is that open-source is better off with copyleft licences. MPL allows you to _use_ the software in any way (without the hassles of (L)GPL), but you must disclose the changes you make, which seems fair to me. Many others prefer permissive licences like MIT or BSD, and I understand that various circumstances might discourage users from using copyleft licences, but that's what open-source is about -- you have a choice to use somebody else's work under their conditions.

**Comment by wesm** [comment]
I understand the ideological basis for copyleft licenses. Unfortunately, the practical outcome of your choice is that it is not a good idea for us to use your software as a dependency in our project which has tens of millions of user installations per month. Personally, I choose the users and if some people use our IP in a selfish way that is the trade-off we've made.

**Comment by foxik** [comment]
I respect your view and policy. But it is your choice not to include MPL-licensed software, so I do not feel I have not chosen the users.

In any way, unilib is no real IP, it is quite a trivial library I needed for NLP projects so I hacked it in several days; but I do believe in copyleft.

**Comment by maartenbreddels** [comment]
> unilib is no real IP, it is quite a trivial library

I agree, if you give 10 good programmers an assignment to create a c++ unicode library from scratch, I think you'll find very similar codes to yours. But that also makes it a waste of time for other programmers to implement this again and again.

I think your implementation is just really good, fast, and clean, and it's a shame that the world has to keep reimplementing unicode libraries similar yours.

I agree that it's not GPL, but as you see, it does limit its use.

No hard feelings, awesome library 👍 , too bad we can't use it under this license.

**Comment by foxik** [comment]
No hard feelings here as well, thanks for your time to explain your views!

The work replication is definitely a very strong argument. On the other hand, as far as I understand, you could just use unilib (have it in the repository as individual files, modify them in any way you want as long as you publish the sources), so it is your decision not to reuse unilib. I understand that it may not be your personal decision and you may not be able to change it, which is why we end up in a deadlock; but for the work I did I want the modifications to be released.

I am happy you like the library; it seems you wanted to use upper/lower/title-casing, so note that unilib currently performs only character-level operations; casing changing the length of the string (like German sharp s) are not implemented yet; the list of these is at https://www.unicode.org/Public/UCD/latest/ucd/SpecialCasing.txt. I am planning a new release (using C++17, string_views, yay!) which will include it.

**Comment by maartenbreddels** [comment]
You're welcome.

Independent of the specific licenses, unilib is a library that is most likely a dependency of another application or library. To have a license that is more restrictive causes friction in adoption, thus less use.

> but for the work I did I want the modifications to be released.

And I think that having more users is will make it more likely for people to contribute back, as most open source *and* closed source development prefer to build on top of other libraries, and not maintain their own fork (e.g. Apache Arrow).

So I think to have the 'lowest level' libraries as permissive as possible is most health for the open-source ecosystem. I agree it allows for more 'abuse', but the upsides (more use and contributions) might make up for that.




> so note that unilib currently performs only character-level operations; casing changing the length of the string (like German sharp s) are not implemented yet; the list of these is at https://www.unicode.org/Public/UCD/latest/ucd/SpecialCasing.txt.

Yes, we were aware of that, and it would be really great if this was implemented!
